title: Luis Mesa
description: Luis Mesa <CV>
author:  Luis Mesa
email: luismesalas@gmail.com

theme: minima

minima:
  skin: auto
  date_format: "%Y-%m-%d"

header_pages:
  - _pages/cv_es.md
  - _pages/cv_en.md

include:
  - _pages

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

linkedin_username: mesa
